### PR TITLE
global logger

### LINKED ISSUE #158: General logger with stream handler and file handler
The project needs a general logger with perhaps the `logging` package for us to develop and debug various parts of the developing copylot package. I don't know what the structure should be, but previously I have set up a 'global' logger that is shared for all the methods.

### PR DESCRIPTION
**Pull request by AhmetCanSolak**
This PR implements an application-wide logger and migrate print statements to logger calls. Closes #158 .

### CODE REVIEW

**Comment by keithchev** [comment]
Since there is only one logger with the name `'application'`, I think the `name` parameter in the log format is not needed. 

I'd also consider adding the module and function names to the log messages, which may be helpful to have in a large project like this with many different modules. The log format would then be the following (note the capital 'N' in `funcName`): 
```
'%(asctime)s - %(levelname)s - %(module)s.%(funcName)s - %(message)s'
```

**Comment by AhmetCanSolak** [comment]
I like your proposal @keithchev , how do you feel about it @edyoshikun ?

**Comment by edyoshikun** [comment]
I like that structure because it's easier to localize the call. Thank you both

**Review by edyoshikun — APPROVED** [review]
Thank you for implementing this! I tested this in new files. LGTM!

**Review by edyoshikun — APPROVED** [review]
adjusted the black formatting so it passes CI. Now it's good to go!

**Pull request merged**
